version: '3.4'

services:

  nginx:
    build: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./buildkit:/buildkit"
      - "./manage:/manage"
      - "amp:/home/buildkit/.amp"
    links:
      - fpm
  fpm:
    build: fpm
    volumes:
      - "./buildkit:/buildkit"
      - "./manage:/manage"
    links:
      - mysql

  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: buildkit
    volumes:
      - mysql:/var/lib/mysql

  cli:
    build: cli
    volumes:
      - "./buildkit:/buildkit"
      - "amp:/home/buildkit/.amp"

  phpmyadmin:
    build: phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql

  mail:
    image: djfarrelly/maildev
    ports:
      - "8082:80"

volumes:
  amp:
  mysql:
