version: '3.4'

services:

  nginx:
    build: nginx
    ports:
      - "8080:8080"
    volumes:
      - "buildkit:/buildkit"
      - "./manage:/manage"
      - "amp:/home/buildkit/.amp"
    links:
      - civicrm

  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: buildkit
    volumes:
      - mysql:/var/lib/mysql

  civicrm:
    build: civicrm
    volumes:
      - "buildkit:/buildkit"
      - "amp:/home/buildkit/.amp"
    links:
      - mysql

  phpmyadmin:
    build: phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysql:mysql # simplify to just mysql?
    environment:
      PMA_HOST: mysql

  mail:
    image: djfarrelly/maildev
    ports:
      - "8082:80"

volumes:
  amp:
  mysql:
  buildkit:
