version: '3.4'

services:

  civicrm:
    build: civicrm
    volumes:
      - "buildkit:/buildkit"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: buildkit
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysql:mysql # simplify to just mysql?
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: buildkit

  mail:
    image: djfarrelly/maildev
    ports:
      - "8082:80"

volumes:
  mysql:
  buildkit:
