version: '3.4'

services:

  nginx:
    build: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./build:/home/buildkit/civicrm-buildkit/build"
      - "amp:/home/buildkit/.amp"
    links:
      - fpm
  fpm:
    build: fpm
    volumes:
      - "./build:/home/buildkit/civicrm-buildkit/build"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: buildkit

  cli:
    build: cli
    volumes:
      - "./build:/home/buildkit/civicrm-buildkit/build"
      - "amp:/home/buildkit/.amp"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql

  mail:
    image: djfarrelly/maildev
    ports:
      - "8082:80"

volumes:
  amp:
